### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Minesound** [GoyoStach/Obsidian-to-Astro#1]
I want to use your source code to build a website for commercial and personal ends. But, I couldn't find any licensing info, so is it all rights reserved and only for educational fair use? Can you clarify the licensing situation? Thanks!

**Comment by Goyostash** [comment]
Hello @Minesound and thanks for showing interest. Although the code is available as of now, it will be private once I am finished with the developments. 
So all the content is **all rights reserved.**
I will update the licence of the project once i get some time to clearly state my position on the matter. Best regards
